name: lint
on: push

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: test
        run: |
          docker-compose -f docker/ci/docker-compose.yml run ci run-frontend-lint
