name: Setup Tests
on:
  workflow_call:

jobs:
  units:
    name: Setup Tests
    runs-on: ubuntu-latest
    env:
      CI_CACHE_PATH: "/tmp/cache"
      CI_RETRY_COUNT: 3
      LOCAL_DEV_CHECK: 1
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: cache
        uses: actions/cache@v2
        with:
          path: /tmp/cache
          key: ${{ runner.os }}-core-tests-units-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-core-tests-units-
            ${{ runner.os }}-core-tests-
      - name: build
        run: |
          docker-compose -f docker/ci/docker-compose.yml build --pull ci
