name: test
on: push

jobs:
  test-resuable-angular-workflow:
    uses: bitcrowd/openproject-proto_plugin/.github/workflows/angular-unit-tests.yml@docker
  test-resuable-angular-workflow:
    uses: bitcrowd/openproject-proto_plugin/.github/workflows/rspec-unit-tests.yml@docker
  test-resuable-angular-workflow:
    uses: bitcrowd/openproject-proto_plugin/.github/workflows/rspec-features-tests.yml@docker