name: test
on: push

jobs:
  setup-tests:
    uses: bitcrowd/openproject-proto_plugin/.github/workflows/workflow-setup-tests.yml@v1
  angular-tests:
    name: Angular-Units
    runs-on: ubuntu-latest
    env:
      CI_CACHE_PATH: "/tmp/cache"
      CI_RETRY_COUNT: 3
      LOCAL_DEV_CHECK: 1
    steps:
      - name: build
        run: |
          docker-compose -f docker/ci/docker-compose.yml build --pull ci
      - name: test
        run: |
          docker-compose -f docker/ci/docker-compose.yml run ci setup-tests run-units
      - name: cleanup
        if: ${{ always() }}
        run: |
          docker-compose -f docker/ci/docker-compose.yml down --remove-orphans -t 10
          sudo chown -R $(whoami):$(id -ng) $CI_CACHE_PATH
  # rspec:
  #   name: Rspec
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 60
  #   env:
  #     CI_CACHE_PATH: "/tmp/cache"
  #     LOCAL_DEV_CHECK: 1
  #     CI_RETRY_COUNT: 3
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: cache
  #       uses: actions/cache@v2
  #       with:
  #         path: /tmp/cache
  #         key: ${{ runner.os }}-core-tests-features-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-core-tests-features-
  #           ${{ runner.os }}-core-tests-
  #     - name: build
  #       run: |
  #         docker-compose -f docker/ci/docker-compose.yml build --pull ci
  #     - name: test
  #       run: |
  #         docker-compose -f docker/ci/docker-compose.yml run ci setup-tests run-rspec
  #     - name: cleanup
  #       if: ${{ always() }}
  #       run: |
  #         docker-compose -f docker/ci/docker-compose.yml down --remove-orphans -t 10
  #         sudo chown -R $(whoami):$(id -ng) $CI_CACHE_PATH
